namespace Freeboard.Persistence.Auth;

/// <summary>
/// A user profile read model. NEVER carries the password hash; credentials live in a
/// separate store/table.
/// </summary>
public sealed record UserRow(
    string Id,
    string Email,
    string EmailNormalized,
    string Name,
    string GlobalRole,
    bool Enabled,
    bool ForcePasswordReset,
    bool MfaEnabled,
    DateTime CreatedAt,
    DateTime UpdatedAt);

/// <summary>Values needed to create a user. The id is generated by the store via <see cref="IUlidFactory"/>.</summary>
public sealed record NewUser(string Email, string Name, string GlobalRole);

/// <summary>
/// A password credential read model: the PHC Argon2id hash plus the keyed-secret version
/// it was produced under (for rotation). Read only by the verify path, never by a
/// profile read. <paramref name="CredentialVersion"/> is the monotonic epoch bumped on
/// every password change/reset; a session stores the version it was issued under and is rejected
/// when it goes stale.
/// </summary>
public sealed record PasswordCredentialRow(string UserId, string PasswordHash, int SecretVersion, int CredentialVersion);
