namespace Freeboard.Persistence.Auth;

/// <summary>
/// A stored WebAuthn/FIDO2 credential. The web app runs the ceremonies; this layer
/// only persists the row. <see cref="SignCount"/> is the last counter seen.
/// </summary>
public sealed record WebAuthnCredentialRow(
    string Id,
    string UserId,
    byte[] CredentialId,
    byte[] PublicKey,
    long SignCount,
    byte[] UserHandle,
    string? Aaguid,
    string? Transports,
    string? CredType,
    bool? IsBackupEligible,
    bool? IsBackedUp,
    string? Nickname,
    DateTime CreatedAt,
    DateTime? LastUsedAt);

/// <summary>Values needed to persist a new WebAuthn credential. The id is generated by the store.</summary>
public sealed record NewWebAuthnCredential(
    string UserId,
    byte[] CredentialId,
    byte[] PublicKey,
    long SignCount,
    byte[] UserHandle,
    string? Aaguid,
    string? Transports,
    string? CredType,
    bool? IsBackupEligible,
    bool? IsBackedUp,
    string? Nickname);

/// <summary>
/// WebAuthn credential store. Stores credential rows, looks them up by credential id,
/// lists/removes them per user, and updates the sign counter under the synced-passkey rule.
/// No Fido2 dependency: ceremony verification lives in the web app.
/// </summary>
public interface IWebAuthnCredentialStore
{
    /// <summary>Persists a new credential with a generated ULID id. Returns the stored row.</summary>
    Task<WebAuthnCredentialRow> AddAsync(NewWebAuthnCredential credential, CancellationToken cancellationToken = default);

    /// <summary>Looks up a credential by its raw <c>credential_id</c>. Returns null if absent.</summary>
    Task<WebAuthnCredentialRow?> FindByCredentialIdAsync(byte[] credentialId, CancellationToken cancellationToken = default);

    Task<IReadOnlyList<WebAuthnCredentialRow>> ListByUserAsync(string userId, CancellationToken cancellationToken = default);

    /// <summary>Removes one credential by its id. Returns true if a row was removed.</summary>
    Task<bool> RemoveAsync(string id, CancellationToken cancellationToken = default);

    /// <summary>
    /// Applies the assertion sign counter to the row, stamping <c>last_used_at</c>. Enforces
    /// <see cref="WebAuthnSignCounter.IsAcceptable"/>: returns false (no write) on a rejected
    /// regression, true on an accepted counter.
    /// </summary>
    Task<bool> UpdateSignCountAsync(string id, long presentedSignCount, DateTime usedAt, CancellationToken cancellationToken = default);
}

/// <summary>
/// The synced-passkey sign-counter rule, kept pure and unit-testable. Synced passkeys
/// report and keep a counter of 0, so a 0 is always accepted. A regression is rejected ONLY
/// when both the stored and presented counters are above 0 and the presented value does not
/// exceed the stored value (a cloned-authenticator signal). Otherwise the counter is accepted.
/// </summary>
public static class WebAuthnSignCounter
{
    /// <summary>True if <paramref name="presented"/> may be accepted against <paramref name="stored"/>.</summary>
    public static bool IsAcceptable(long stored, long presented)
    {
        if (presented == 0)
        {
            return true;
        }

        if (stored > 0 && presented <= stored)
        {
            return false;
        }

        return true;
    }
}
